import Head from 'next/head'
import { useRef, useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {

  const [myStyle, setMyStyle]=useState(styles.toggle);
  const [myStyle2, setMyStyle2]=useState(styles.showcase);
  const styleRef=useRef(null);
  
  const toggleFnc=()=>{
    if (styleRef.current.classList.value===(`${styles.toggle} ${styles.active}`)){
      setMyStyle(`${styles.toggle}`)
      setMyStyle2(`${styles.showcase}`)
    } else {
      setMyStyle(`${styles.toggle} ${styles.active}`)
      setMyStyle2(`${styles.showcase} ${styles.active}`)
    }
    // setMyStyle(`${styles.toggle} ${styles.active}`);
  }



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={myStyle2}>
          <header>
            <h1 className={styles.logo}>Fantasy</h1>
            <div ref={styleRef} onClick={toggleFnc} className={myStyle}></div>
          </header>
          <video src="fantasy.mp4" autoPlay loop muted></video>
          <div className={styles.overlay}></div>
          <div className={styles.text}>
            <h2>Fantasy Line</h2>
            <h3>Expore Something New</h3>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Necessitatibus, excepturi! Dolore est amet natus assumenda?</p>
            <a href="#">Dive into</a>
          </div>
          <ul className={styles.social}>
            <li><a href="#"><img src="facebook.png" alt="" /></a></li>
            <li><a href="#"><img src="twitter.png" alt="" /></a></li>
            <li><a href="#"><img src="instagram.png" alt="" /></a></li>
          </ul>
        </section>
        <div className={styles.menu}>
          <ul>
            <li><a href="">Home</a></li>
            <li><a href="">Contact</a></li>
            <li><a href="">Destination</a></li>
            <li><a href="">Suppoer</a></li>
          </ul>
        </div>
      </main>
    </div>
  )
}
